pacbins: list package files installed under /usr/bin

diff --git a/bash/.config/bash/bash-customization b/bash/.config/bash/bash-customization
--- a/bash/.config/bash/bash-customization
+++ b/bash/.config/bash/bash-customization
@@ -21,6 +21,23 @@ alias fh="free -h"
 
 ec () { echo $?; }
 
+# pacbins: print the list of files installed under /usr/bin belonging to a
+# certain Pacman package.
+pacbins() {
+    if [[ $# -eq 1 ]]; then
+	outfile="$(mktemp /tmp/pacbin.XXXXXXXXXX)" &&
+	    pacman -Qql "$1" > "$outfile" 2> /dev/null &&
+	    grep -E "/usr/bin/[a-zA-Z0-9]{1}" "$outfile" ||
+		(rm "$outfile";
+		 >&2 echo "error: package $1 isn't installed or doesn't exist";
+		 return 1) &&
+		    rm "$outfile"
+    else
+	>&2 echo "Usage: pacbins [PACKAGE]"
+	return 1
+    fi
+}
+
 export PATH="$HOME/perl5/bin:$HOME/.local/bin:$HOME/.cargo/bin:/usr/share/bcc/tools:$PATH"
 export MANPATH="/usr/share/bcc/man:$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/man:$MANPATH"
 export SBCL_HOME="/usr/lib/sbcl"
